# docker-compose.yml
# ----------------------------------------------------------------------------
# Composes Docker containers and volumes to a runnable application
# ----------------------------------------------------------------------------
#
---
services:

  backend:
    image: docker.cloudtrain.aws.msgoat.eu/cloudtrain/cnj-security-oidc-backend-spring:latest
    ports:
      - "38080:8080"
    environment:
      DOCKER_JAVA_OPTS: "-Xms1g -Xmx1g"
      SPRING_PROFILES_ACTIVE: default
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: https://oidc.cloudtrain.aws.msgoat.eu/realms/cloudtrain/protocol/openid-connect/certs
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: https://oidc.cloudtrain.aws.msgoat.eu/realms/cloudtrain





  